# Fenix Library
# Please refer to the file `LICENSE` in the main directory for license information. 
# For a high level documentation, please visit https://gitlab.com/rebornos-team/fenix/libraries

# AUTHORS
# 1. Shivanand Pattanshetti (shivanand.pattanshetti@gmail.com)
# 2. 

image: python:latest

pages:
  stage: build
  script:
  - apt-get --yes update
  - apt-get --yes install git # for git based dependencies
  - apt-get --yes install build-essential # for using `make`
  - apt-get --yes install gcc python3-dev # for `psutil`, which is a dependency of `fenix_library-analyzing`. pip install does not automatically handle all the dependencies of psutil
  - apt-get --yes install graphviz fontconfig # for diagrams
  - pip install pipenv # install pipenv for reading the pipfile and installing the dev dependencies
  - pipenv install --system --dev # install the dev dependencies so that we have (1) Sphinx and a theme for it, and also (2) for keeping dependencies importable and hence documentable
  - rm -rf public/* # clear out old files
  - cd documentation && make html; cd .. # run Sphinx to generate documentation as html. Information on build is in the makefile and in `conf.py`
  - cp -r documentation/build/html/. public/ # copy the html pages to the public directory
  artifacts:
    paths:
    - public
  only:
  - default
  allow_failure: false

development_pages:
  stage: build
  script:
  - apt-get --yes update
  - apt-get --yes install git # for git based dependencies
  - apt-get --yes install build-essential # for using `make`
  - apt-get --yes install gcc python3-dev # for `psutil`, which is a dependency of `fenix_library-analyzing`. pip install does not automatically handle all the dependencies of psutil
  - apt-get --yes install graphviz fontconfig # for diagrams
  - pip install pipenv # install pipenv for reading the pipfile and installing the dev dependencies
  - pipenv install --system --dev # install the dev dependencies so that we have (1) Sphinx and a theme for it, and also (2) for keeping dependencies importable and hence documentable
  - rm -rf public/* # clear out old files
  - cd documentation && make html; cd .. # run Sphinx to generate documentation as html. Information on build is in the makefile and in `conf.py`
  - cp -r documentation/build/html/. public/ # copy the html pages to the public directory
  only:
  - branches
  except:
  - default
  allow_failure: true

run:
  stage: deploy
  script:
    - pip install twine
    - pip install --upgrade build
    - rm -rf build dist *.egg-info # cleanup old files
    - python -m build # build the package
    - TWINE_PASSWORD=${CI_PYPI_TOKEN} TWINE_USERNAME=__token__ python -m twine upload dist/*
  only:
  - default
  when: manual
  allow_failure: false
